LDRealms = LDRealms or {}

LDRealms[1] = {
    [129] = "enUS", -- Gurubashi
    [131] = "enUS", -- Skywall
    [66] = "enUS", -- Dalaran
    [51] = "enUS", -- Garona
    [103] = "enUS", -- Thunderlord
    [111] = "enUS", -- Dunemaul
    [121] = "enUS", -- Azjol-Nerub
    [127] = "enUS", -- Firetree
    [151] = "enUS", -- Runetotem
    [1579] = "enUS", -- Grizzly Hills
    [1581] = "enUS", -- Galakrond
    [1582] = "enUS", -- Dawnbringer
    [115] = "enUS", -- Draenor
    [1356] = "enUS", -- Sisters of Elune
    [88] = "enUS", -- Cenarion Circle
    [106] = "enUS", -- Aggramar
    [1362] = "enUS", -- Drak'Tharon
    [1072] = "enUS", -- Ravencrest
    [87] = "enUS", -- Windrunner
    [126] = "enUS", -- Scarlet Crusade
    [58] = "enUS", -- Stormreaver
    [67] = "enUS", -- Elune
    [72] = "enUS", -- Shattered Hand
    [73] = "enUS", -- Bleeding Hollow
    [1175] = "enUS", -- Trollbane
    [1355] = "enUS", -- Winterhoof
    [1357] = "enUS", -- Maiev
    [1182] = "enUS", -- Muradin
    [1184] = "enUS", -- Vek'nilash
    [1185] = "enUS", -- Sen'jin
    [74] = "enUS", -- Skullcrusher
    [75] = "enUS", -- Argent Dawn
    [79] = "enUS", -- Destromath
    [80] = "enUS", -- Gorgonnash
    [81] = "enUS", -- Dethecus
    [83] = "enUS", -- Bonechewer
    [84] = "enUS", -- Dragonmaw
    [86] = "enUS", -- Silvermoon
    [90] = "enUS", -- Terenas
    [92] = "enUS", -- Gorefiend
    [95] = "enUS", -- Lightning's Blade
    [96] = "enUS", -- Eonar
    [98] = "enUS", -- Kargath
    [99] = "enUS", -- Llane
    [100] = "enUS", -- Earthen Ring
    [101] = "enUS", -- Laughing Skull
    [102] = "enUS", -- Burning Legion
    [104] = "enUS", -- Malygos
    [105] = "enUS", -- Thunderhorn
    [114] = "enUS", -- Dragonblight
    [116] = "enUS", -- Uldum
    [53] = "enUS", -- Hellscream
    [4] = "enUS", -- Kilrogg
    [82] = "enUS", -- Spinebreaker
    [47] = "enUS", -- Eitrigg
    [89] = "enUS", -- Nathrezim
    [118] = "enUS", -- Feathermoon
    [119] = "enUS", -- Bloodscalp
    [1358] = "enUS", -- Rivendare
    [1359] = "enUS", -- Nordrassil
    [1361] = "enUS", -- Cairne
    [1364] = "enUS", -- Shandris
    [1365] = "enUS", -- Moon Guard
    [1367] = "enUS", -- Nazgrel
    [1368] = "enUS", -- Hydraxis
    [1] = "enUS", -- Lightbringer
    [3] = "enUS", -- Uther
    [5] = "enUS", -- Proudmoore
    [2] = "enUS", -- Cenarius
    [10] = "enUS", -- Blackrock
    [12] = "enUS", -- Silver Hand
    [13] = "enUS", -- Doomhammer
    [14] = "enUS", -- Icecrown
    [16] = "enUS", -- Kel'Thuzad
    [128] = "enUS", -- Frostmane
    [1173] = "enUS", -- Madoran
    [1549] = "enUS", -- Azuremyst
    [1555] = "enUS", -- Auchindoun
    [1556] = "enUS", -- Coilfang
    [1557] = "enUS", -- Shattered Halls
    [1558] = "enUS", -- Blood Furnace
    [1559] = "enUS", -- The Underbog
    [1563] = "enUS", -- Terokkar
    [1564] = "enUS", -- Blade's Edge
    [1565] = "enUS", -- Exodar
    [1566] = "enUS", -- Area 52
    [1572] = "enUS", -- Zangarmarsh
    [1576] = "enUS", -- Fizzcrank
    [70] = "enUS", -- Mannoroth
    [1131] = "enUS", -- Nazjatar
    [1132] = "enUS", -- Malfurion
    [1136] = "enUS", -- Aegwynn
    [1137] = "enUS", -- Akama
    [162] = "enUS", -- Emerald Dream
    [130] = "enUS", -- Smolderthorn
    [54] = "enUS", -- Blackhand
    [55] = "enUS", -- Whisperwind
    [56] = "enUS", -- Archimonde
    [60] = "enUS", -- Stormrage
    [62] = "enUS", -- Medivh
    [63] = "enUS", -- Durotan
    [64] = "enUS", -- Bloodhoof
    [65] = "enUS", -- Khadgar
    [1151] = "enUS", -- Rexxar
    [1344] = "enUS", -- The Forgotten Coast
    [1154] = "enUS", -- Thorium Brotherhood
    [1345] = "enUS", -- Fenris
    [1346] = "enUS", -- Anub'arak
    [1347] = "enUS", -- Blackwater Raiders
    [1348] = "enUS", -- Vashj
    [1349] = "enUS", -- Korialstrasz
    [1351] = "enUS", -- Darrowmere
    [1354] = "enUS", -- Shu'halo
    [1165] = "enUS", -- Arathor
    [160] = "enUS", -- Staghelm
    [123] = "enUS", -- Eldre'Thalas
    [1271] = "enUS", -- Dentarg
    [1286] = "enUS", -- Demon Soul
    [124] = "enUS", -- Spirestone
    [6] = "enUS", -- Hyjal
    [1295] = "enUS", -- Lethon
    [1296] = "enUS", -- Blackwing Lair
    [1297] = "enUS", -- Arygos
    [1258] = "enUS", -- Duskwood
    [57] = "enUS", -- Illidan
    [68] = "enUS", -- Lothar
    [76] = "enUS", -- Sargeras
    [77] = "enUS", -- Azgalor
    [78] = "enUS", -- Magtheridon
    [94] = "enUS", -- Shadowmoon
    [1425] = "esMX", -- Drakkari
    [1427] = "esMX", -- Ragnaros
    [125] = "enUS", -- Shadow Council
    [1067] = "enUS", -- Cho'gall
    [1068] = "enUS", -- Gul'dan
    [1069] = "enUS", -- Kael'thas
    [1070] = "enUS", -- Alexstrasza
    [1071] = "enUS", -- Kirin Tor
    [1075] = "enUS", -- Balnazzar
    [1140] = "enUS", -- Drak'thul
    [1141] = "enUS", -- Garithos
    [1142] = "enUS", -- Hakkar
    [1143] = "enUS", -- Khaz Modan
    [1145] = "enUS", -- Mug'thol
    [1147] = "enUS", -- Kul Tiras
    [1148] = "enUS", -- Malorne
    [1342] = "enUS", -- Echo Isles
    [61] = "enUS", -- Zul'jin
    [1259] = "enUS", -- Zuluhed
    [1260] = "enUS", -- Steamwheedle Cartel
    [1262] = "enUS", -- Norgannon
    [1263] = "enUS", -- Thrall
    [163] = "enUS", -- Maelstrom
    [164] = "enUS", -- Twisting Nether
    [155] = "enUS", -- Kalecgos
    [156] = "enUS", -- Ursin
    [157] = "enUS", -- Dark Iron
    [159] = "enUS", -- Wildhammer
    [1369] = "enUS", -- Wyrmrest Accord
    [1370] = "enUS", -- Farstriders
    [1371] = "enUS", -- Borean Tundra
    [1372] = "enUS", -- Quel'dorei
    [1373] = "enUS", -- Garrosh
    [1374] = "enUS", -- Mok'Nathal
    [1375] = "enUS", -- Nesingwary
    [1377] = "enUS", -- Drenden
    [1128] = "enUS", -- Azshara
    [1129] = "enUS", -- Agamaggan
    [1130] = "enUS", -- Lightninghoof
    [1190] = "enUS", -- Baelgun
    [1264] = "enUS", -- Anetheron
    [1265] = "enUS", -- Turalyon
    [1266] = "enUS", -- Haomarush
    [1268] = "enUS", -- Ysondre
    [1270] = "enUS", -- Ysera
    [1276] = "enUS", -- Andorhal
    [1277] = "enUS", -- Executus
    [1280] = "enUS", -- Black Dragonflight
    [1282] = "enUS", -- Altar of Storms
    [1283] = "enUS", -- Uldaman
    [1284] = "enUS", -- Aerie Peak
    [1285] = "enUS", -- Onyxia
    [1287] = "enUS", -- Gnomeregan
    [1289] = "enUS", -- The Venture Co
    [1290] = "enUS", -- Sentinels
    [1291] = "enUS", -- Jaedenar
    [1292] = "enUS", -- Tanaris
    [1293] = "enUS", -- Alterac Mountains
    [1294] = "enUS", -- Undermine
    [11] = "enUS", -- Tichondrius
    [1353] = "enUS", -- Bladefist
    [1570] = "enUS", -- The Scryers
    [91] = "enUS", -- Burning Blade
    [113] = "enUS", -- Suramar
    [1360] = "enUS", -- Tortheldrin
    [8] = "enUS", -- Ner'zhul
    [52] = "enUS", -- Alleria
    [15] = "enUS", -- Deathwing
    [69] = "enUS", -- Arthas
    [1139] = "enUS", -- Draka
    [1567] = "enUS", -- Velen
    [7] = "enUS", -- Frostwolf
    [1350] = "enUS", -- Misha
    [153] = "enUS", -- Moonrunner
    [1578] = "enUS", -- Ghostlands
    [93] = "enUS", -- Eredar
    [1146] = "enUS", -- Korgath
    [154] = "enUS", -- Detheroc
    [1352] = "enUS", -- Ravenholdt
    [3234] = "ptBR", -- Gallywix
    [107] = "enUS", -- Crushridge
    [109] = "enUS", -- Daggerspine
    [110] = "enUS", -- Stormscale
    [112] = "enUS", -- Boulderfist
    [108] = "enUS", -- Stonemaul
    [158] = "enUS", -- Greymane
    [9] = "enUS", -- Kil'jaeden
    [122] = "enUS", -- Perenolde
    [85] = "enUS", -- Shadowsong
    [59] = "enUS", -- Mal'Ganis
    [120] = "enUS", -- Darkspear
    [117] = "enUS", -- Bronzebeard
    [97] = "enUS", -- Gilneas
    [1138] = "enUS", -- Chromaggus
    [1363] = "enUS", -- Antonidas
    [71] = "enUS", -- Warsong
    [1428] = "esMX", -- Quel'Thalas
    [1278] = "enUS", -- Dalvengyr
    [1267] = "enUS", -- Scilla
    [1288] = "enUS", -- Anvilmar
    [3207] = "ptBR", -- Goldrinn
    [3208] = "ptBR", -- Nemesis
    [3209] = "ptBR", -- Azralon
    [3210] = "ptBR", -- Tol Barad
    [3733] = "enUS", -- Dreadmaul
    [3721] = "enUS", -- Caelestrasz
    [3734] = "enUS", -- Nagrand
    [3722] = "enUS", -- Aman'Thul
    [3723] = "enUS", -- Barthilas
    [3724] = "enUS", -- Thaurissan
    [3735] = "enUS", -- Dath'Remar
    [3725] = "enUS", -- Frostmourne
    [3726] = "enUS", -- Khaz'goroth
    [3736] = "enUS", -- Jubei'Thos
    [3737] = "enUS", -- Gundrak
    [3738] = "enUS", -- Saurfang
}

LDRealms[2] = "koKR"

LDRealms[3] = {
    [1080] = "enGB", -- Khadgar
    [1083] = "enGB", -- Chromaggus
    [1084] = "enGB", -- Dentarg
    [1086] = "frFR", -- La Croisade écarlate
    [547] = "enGB", -- Runetotem
    [548] = "enGB", -- Shadowsong
    [549] = "enGB", -- Silvermoon
    [511] = "enGB", -- Sunstrider
    [1087] = "enGB", -- Executus
    [1089] = "enGB", -- Mazrigos
    [1596] = "enGB", -- Karazhan
    [1597] = "enGB", -- Auchindoun
    [1598] = "enGB", -- Shattered Halls
    [1602] = "ruRU", -- Gordunni
    [1604] = "ruRU", -- Soulflayer
    [1605] = "ruRU", -- Deathguard
    [1606] = "enGB", -- Sporeggar
    [1607] = "deDE", -- Nethersturm
    [1608] = "deDE", -- Shattrath
    [1609] = "ruRU", -- Deepholm
    [1612] = "deDE", -- Echsenkessel
    [1613] = "deDE", -- Blutkessel
    [1614] = "ruRU", -- Galakrond
    [1616] = "ruRU", -- Razuvious
    [1617] = "ruRU", -- Deathweaver
    [551] = "enGB", -- Terenas
    [552] = "enGB", -- Thunderhorn
    [553] = "enGB", -- Turalyon
    [554] = "enGB", -- Ravencrest
    [556] = "enGB", -- Shattered Hand
    [558] = "enGB", -- Spinebreaker
    [560] = "enGB", -- Stormscale
    [561] = "enGB", -- Earthen Ring
    [562] = "deDE", -- Alexstrasza
    [563] = "deDE", -- Alleria
    [564] = "deDE", -- Antonidas
    [566] = "deDE", -- Blackhand
    [567] = "deDE", -- Gilneas
    [568] = "deDE", -- Kargath
    [569] = "deDE", -- Khaz'goroth
    [571] = "deDE", -- Madmortem
    [573] = "deDE", -- Zuluhed
    [574] = "deDE", -- Nozdormu
    [575] = "deDE", -- Perenolde
    [577] = "deDE", -- Aegwynn
    [600] = "deDE", -- Dun Morogh
    [604] = "deDE", -- Thrall
    [605] = "deDE", -- Theradras
    [606] = "enGB", -- Genjuros
    [607] = "enGB", -- Balnazzar
    [609] = "deDE", -- Wrathbringer
    [1090] = "enGB", -- Talnivarr
    [1091] = "enGB", -- Emeriss
    [1092] = "enGB", -- Drak'thul
    [1093] = "enGB", -- Ahn'Qiraj
    [1097] = "deDE", -- Ysera
    [1098] = "deDE", -- Malygos
    [1104] = "deDE", -- Anetheron
    [1105] = "deDE", -- Nazjatar
    [1106] = "deDE", -- Tichondrius
    [1117] = "enGB", -- Steamwheedle Cartel
    [1118] = "deDE", -- Die ewige Wacht
    [1119] = "deDE", -- Die Todeskrallen
    [1121] = "deDE", -- Die Arguswacht
    [1122] = "frFR", -- Uldaman
    [1127] = "frFR", -- Confrérie du Thorium
    [507] = "enGB", -- Dragonblight
    [1306] = "enGB", -- Tarren Mill
    [1381] = "esES", -- C'Thun
    [1391] = "enGB", -- Alonsus
    [1416] = "enGB", -- Blade's Edge
    [505] = "enGB", -- Doomhammer
    [513] = "enGB", -- Twilight's Hammer
    [526] = "enGB", -- Daggerspine
    [546] = "frFR", -- Sargeras
    [508] = "enGB", -- Emerald Dream
    [623] = "enGB", -- Quel'Thalas
    [522] = "enGB", -- Bloodscalp
    [523] = "enGB", -- Burning Blade
    [525] = "enGB", -- Crushridge
    [528] = "enGB", -- Dragonmaw
    [529] = "enGB", -- Dunemaul
    [531] = "deDE", -- Dethecus
    [535] = "deDE", -- Durotan
    [500] = "enGB", -- Aggramar
    [501] = "enGB", -- Arathor
    [503] = "enGB", -- Azjol-Nerub
    [506] = "enGB", -- Draenor
    [510] = "frFR", -- Vol'jin
    [512] = "frFR", -- Arak-arahm
    [515] = "enGB", -- Zenedar
    [518] = "enGB", -- Agamaggan
    [521] = "enGB", -- Bladefist
    [1337] = "frFR", -- Culte de la Rive noire
    [536] = "enGB", -- Argent Dawn
    [610] = "deDE", -- Onyxia
    [612] = "deDE", -- Nefarian
    [614] = "deDE", -- Das Syndikat
    [621] = "enGB", -- Laughing Skull
    [624] = "enGB", -- Neptulon
    [625] = "enGB", -- Twisting Nether
    [627] = "enGB", -- The Maelstrom
    [630] = "enGB", -- Bloodfeather
    [632] = "enGB", -- Frostwhisper
    [633] = "enGB", -- Kor'gall
    [635] = "enGB", -- Defias Brotherhood
    [642] = "frFR", -- Rashgarroth
    [647] = "frFR", -- Les Sentinelles
    [1331] = "frFR", -- Suramar
    [1401] = "deDE", -- Garrosh
    [1406] = "deDE", -- Arygos
    [1407] = "deDE", -- Teldrassil
    [1409] = "deDE", -- Lordaeron
    [1413] = "ptPT", -- Aggra (Português)
    [1415] = "enGB", -- Terokkar
    [565] = "deDE", -- Baelgun
    [545] = "frFR", -- Cho'gall
    [618] = "enGB", -- Nordrassil
    [628] = "enGB", -- Sylvanas
    [641] = "frFR", -- Drek'Thar
    [1588] = "enGB", -- Ghostlands
    [1595] = "enGB", -- The Sha'tar
    [1620] = "frFR", -- Chants éternels
    [1621] = "frFR", -- Marécage de Zangar
    [1624] = "frFR", -- Naxxramas
    [578] = "deDE", -- Arthas
    [579] = "deDE", -- Azshara
    [580] = "deDE", -- Blackmoore
    [582] = "deDE", -- Destromath
    [583] = "deDE", -- Eredar
    [585] = "deDE", -- Frostwolf
    [589] = "deDE", -- Kil'jaeden
    [590] = "deDE", -- Mal'Ganis
    [592] = "deDE", -- Zirkel des Cenarius
    [629] = "enGB", -- Vashj
    [542] = "frFR", -- Hyjal
    [1323] = "deDE", -- Ulduar
    [1615] = "ruRU", -- Howling Fjord
    [519] = "enGB", -- Al'Akir
    [559] = "enGB", -- Stormreaver
    [622] = "enGB", -- Magtheridon
    [637] = "enGB", -- Lightning's Blade
    [537] = "frFR", -- Kirin Tor
    [539] = "frFR", -- Archimonde
    [540] = "frFR", -- Elune
    [1307] = "enGB", -- Chamber of Aspects
    [1308] = "enGB", -- Ravenholdt
    [1309] = "itIT", -- Pozzo dell'Eternità
    [1310] = "enGB", -- Eonar
    [1298] = "enGB", -- Vek'nilash
    [1300] = "enGB", -- Frostmane
    [504] = "enGB", -- Bloodhoof
    [543] = "frFR", -- Kael'thas
    [638] = "enGB", -- Haomarush
    [640] = "frFR", -- Khaz Modan
    [645] = "frFR", -- Varimathras
    [646] = "enGB", -- Hakkar
    [581] = "deDE", -- Blackrock
    [588] = "deDE", -- Kel'Thuzad
    [591] = "deDE", -- Mannoroth
    [593] = "deDE", -- Proudmoore
    [509] = "frFR", -- Garona
    [1317] = "enGB", -- Darkmoon Faire
    [1318] = "deDE", -- Vek'lor
    [1319] = "deDE", -- Mug'thol
    [1320] = "deDE", -- Taerar
    [1321] = "deDE", -- Dalvengyr
    [1322] = "deDE", -- Rajaxx
    [1324] = "deDE", -- Malorne
    [1326] = "deDE", -- Der abyssische Rat
    [1327] = "deDE", -- Der Mithrilorden
    [1330] = "deDE", -- Ambossar
    [1332] = "frFR", -- Krasus
    [1334] = "frFR", -- Arathi
    [1335] = "frFR", -- Ysondre
    [1336] = "frFR", -- Eldre'Thalas
    [1311] = "enGB", -- Kilrogg
    [1313] = "enGB", -- Wildhammer
    [1314] = "enGB", -- Saurfang
    [1316] = "itIT", -- Nemesis
    [1623] = "ruRU", -- Fordragon
    [1625] = "ruRU", -- Borean Tundra
    [1626] = "frFR", -- Les Clairvoyants
    [557] = "enGB", -- Skullcrusher
    [570] = "deDE", -- Lothar
    [533] = "frFR", -- Sinstralis
    [615] = "deDE", -- Terrordar
    [1096] = "enGB", -- Scarshield Legion
    [1082] = "enGB", -- Kul Tiras
    [550] = "enGB", -- Stormrage
    [544] = "frFR", -- Ner'zhul
    [1378] = "esES", -- Dun Modr
    [1379] = "esES", -- Zul'jin
    [1380] = "esES", -- Uldum
    [1382] = "esES", -- Sanguino
    [1383] = "esES", -- Shen'dralar
    [1384] = "esES", -- Tyrande
    [1385] = "esES", -- Exodar
    [1387] = "esES", -- Los Errantes
    [1388] = "enGB", -- Lightbringer
    [1389] = "enGB", -- Darkspear
    [1392] = "enGB", -- Burning Steppes
    [1393] = "enGB", -- Bronze Dragonflight
    [1394] = "enGB", -- Anachronos
    [1395] = "esES", -- Colinas Pardas
    [1400] = "deDE", -- Un'Goro
    [541] = "frFR", -- Illidan
    [1099] = "deDE", -- Rexxar
    [1611] = "deDE", -- Festung der Stürme
    [587] = "deDE", -- Gul'dan
    [502] = "enGB", -- Aszune
    [1312] = "enGB", -- Aerie Peak
    [639] = "enGB", -- Xavius
    [643] = "frFR", -- Throk'Feroth
    [1386] = "esES", -- Minahonda
    [1328] = "deDE", -- Tirion
    [602] = "deDE", -- Sen'jin
    [1088] = "enGB", -- Trollbane
    [601] = "deDE", -- Aman'Thul
    [1081] = "enGB", -- Bronzebeard
    [1618] = "deDE", -- Die Aldor
    [1622] = "frFR", -- Temple noir
    [1925] = "ruRU", -- Eversong
    [1926] = "ruRU", -- Thermaplugg
    [1927] = "ruRU", -- Grom
    [1928] = "ruRU", -- Goldrinn
    [1929] = "ruRU", -- Blackscar
    [516] = "deDE", -- Forscherliga
    [1123] = "frFR", -- Eitrigg
    [1405] = "deDE", -- Todeswache
    [538] = "frFR", -- Dalaran
    [584] = "deDE", -- Frostmourne
    [572] = "deDE", -- Malfurion
    [616] = "deDE", -- Krag'jin
    [586] = "deDE", -- Gorgonnash
    [524] = "enGB", -- Burning Legion
    [1417] = "enGB", -- Azuremyst
    [608] = "deDE", -- Anub'arak
    [611] = "deDE", -- Nera'thor
    [613] = "deDE", -- Kult der Verdammten
    [617] = "deDE", -- Der Rat von Dalaran
    [619] = "enGB", -- Hellscream
    [626] = "enGB", -- Ragnaros
    [631] = "enGB", -- Darksorrow
    [636] = "enGB", -- The Venture Co
    [1303] = "enGB", -- Grim Batol
    [1304] = "enGB", -- Jaedenar
    [1305] = "enGB", -- Kazzak
    [1085] = "enGB", -- Moonglade
    [644] = "frFR", -- Conseil des Ombres
    [594] = "deDE", -- Nathrezim
    [1619] = "deDE", -- Das Konsortium
    [1299] = "enGB", -- Boulderfist
    [527] = "enGB", -- Deathwing
    [1404] = "deDE", -- Area 52
    [1333] = "deDE", -- Die Nachtwache
    [1924] = "ruRU", -- Booty Bay
    [1603] = "ruRU", -- Lich King
    [1587] = "enGB", -- Hellfire
    [1301] = "enGB", -- Outland
    [1610] = "ruRU", -- Greymane
    [517] = "frFR", -- Medivh
    [576] = "deDE", -- Die Silberne Hand
    [1589] = "enGB", -- Nagrand
    [1922] = "ruRU", -- Azuregos
    [1923] = "ruRU", -- Ashenvale
    [1408] = "deDE", -- Norgannon
}

LDRealms[4] = "zhTW"

LDRealms[5] = "zhCN"

